# build Configuration, i.e. Debug, Release, etc.
configuration: Release

dotnet_csproj:
  patch: true
  file: 'VtConnect\VtConnect.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# scripts to run before build
before_build:
  - dotnet restore .\VtConnect\VtConnect.csproj

build_script:
  - dotnet build .\VtConnect\VtConnect.csproj

artifacts:
  - path: .\VtConnect\bin\Release\*.nupkg

deploy_script:
  dotnet nuget push .\VtConnect\bin\Release\*.nupkg -k oy2iqn5zue2grblovrcalkxggjoyprlubfamnr5nvqzloq -s https://api.nuget.org/v3/index.json
